### PR TITLE
Add the packaging metadata to build the honeytail snap

### PR DESCRIPTION
**Pull request by elopio**
This is a package for the installation of apps that works in most Linux distributions.
Landing it upstream will enable builds that then can be distributed to many users through the Ubuntu store.

### CODE REVIEW

**Comment by elopio** [comment]
You can find more information about snapcraft here: http://snapcraft.io/

To test it in an Ubuntu 16.04 machine:

    $ sudo apt install git snapcraft
    $ sudo snap install core  # needed to build using the classic confinement
    $ git clone https://github.com/elopio/honeytail
    $ cd honeytail
    $ git checkout snapcraft
    $ snapcraft
    $ sudo snap install *.snap --dangerous --classic 

(dangerous because the snap you build yourself doesn't come signed from the trusted store, classic because a simple first step to develop a snap is to not use the strict confinement.)

This snap, of course, is a first step. It needs more testing, but that's where the edge channel in the store can help. Push it there, and you can tell early adopters and trusted users who want to help to give it a try and provide feedback.

If you have any questions or comments, please let me know.

**Comment by popey** [comment]
Anyone have a chance to test this? Would be great to get honeytail built and pushed to the snap store.

**Comment by maplebed** [comment]
sorry it's been slow - but it's on my schedule for this week.

**Comment by popey** [comment]
Hiya, any chance this can get landed? :)

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now. Looking at it, the snapcraft file form has changed, we've moved CI, etc, so need a fair amount of work before we could accept.

Feel free to re-open, if it’s still relevant.

**Pull request closed without merging**
